import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Quotation } from '../types';

export const generatePO = (quotation: Quotation) => {
  console.log('Starting PO generation for:', quotation.poNo || quotation.rfqNo);
  
  try {
    const doc = new jsPDF();
    console.log('jsPDF instance created');

    // Add Logo
    try {
      console.log('Attempting to add logo...');
      // Use full URL for logo to be safe
      const logoUrl = window.location.origin + '/logo.png';
      doc.addImage(logoUrl, 'PNG', 15, 15, 40, 15);
      console.log('Logo added successfully');
    } catch (e) {
      console.error('Could not load logo in PDF, skipping logo.', e);
    }

    // Header Info
    doc.setFontSize(20);
    doc.setTextColor(40);
    doc.text('PURCHASE ORDER', 140, 25);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`PO Number: ${quotation.poNo || 'N/A'}`, 140, 32);
    doc.text(`Date: ${quotation.poDate || new Date().toLocaleDateString()}`, 140, 37);

    // Vendor & Customer Info
    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text('Vendor:', 15, 45);
    doc.setFont('helvetica', 'bold');
    doc.text(quotation.supplier || '', 15, 51);
    doc.setFont('helvetica', 'normal');
    doc.text(quotation.supplierEmail || '', 15, 57);

    doc.text('Ship To:', 100, 45);
    doc.setFont('helvetica', 'bold');
    doc.text('OceanWharf Marine', 100, 51);
    doc.setFont('helvetica', 'normal');
    doc.text(`Vessel: ${quotation.vessel || ''}`, 100, 57);
    doc.text(`Port: ${quotation.port || ''}`, 100, 63);

    // Quotation Details
    doc.setDrawColor(200);
    doc.line(15, 70, 195, 70);
    
    doc.setFontSize(9);
    doc.text(`RFQ No: ${quotation.rfqNo || ''}`, 15, 77);
    doc.text(`Requisition No: ${quotation.requisitionNo || ''}`, 70, 77);
    doc.text(`Payment Terms: ${quotation.paymentTerms || ''}`, 130, 77);

    // Items Table
    console.log('Preparing table data...');
    const tableData = (quotation.lineItems || []).map(item => [
      item.itemCode || '',
      item.itemDescription || '',
      item.quantity || 0,
      item.primaryUnit || '',
      (item.unitPrice || 0).toFixed(2),
      (item.discountPercentage || 0) + '%',
      (item.netTotal || 0).toFixed(2)
    ]);

    console.log('Rendering autotable...');
    autoTable(doc, {
      startY: 85,
      head: [['Code', 'Description', 'Qty', 'Unit', 'Price', 'Disc%', 'Total']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [0, 102, 204] },
      margin: { top: 10 },
    });

    // Totals
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.text(`Gross Total: ${quotation.currency || ''} ${(quotation.grossTotal || 0).toFixed(2)}`, 140, finalY);
    
    if (quotation.headerDiscountPercentage > 0) {
      doc.text(`Header Discount (${quotation.headerDiscountPercentage}%): -${(quotation.totalDiscount || 0).toFixed(2)}`, 140, finalY + 6);
      doc.setFont('helvetica', 'bold');
      doc.text(`Net Total: ${quotation.currency || ''} ${(quotation.overallTotal || 0).toFixed(2)}`, 140, finalY + 12);
    } else {
      doc.setFont('helvetica', 'bold');
      doc.text(`Net Total: ${quotation.currency || ''} ${(quotation.overallTotal || 0).toFixed(2)}`, 140, finalY + 6);
    }

    // Footer / Comments
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    if (quotation.comments) {
      doc.text('Comments:', 15, finalY + 20);
      doc.text(quotation.comments || '', 15, finalY + 25, { maxWidth: 180 });
    }

    doc.text('Generated by OceanWharf Marine Procurement System', 105, 285, { align: 'center' });

    console.log('Saving PDF...');
    doc.save(`PO_${quotation.poNo || quotation.rfqNo || 'Order'}.pdf`);
    console.log('PDF saved successfully!');
  } catch (error) {
    console.error('CRITICAL ERROR during PO PDF generation:', error);
    alert('An error occurred while generating the PO PDF. Please check the console for details.');
  }
};
